### ISSUE TITLE
Calculation of Wavelet Coefficient

### ISSUE THREAD

**Issue by abhi-rf** [Eilene/GWNN#1]
Hi, 
I was studying the paper and code. Could you please help me find where have you calculated the wavelet coefficient as explained in the paper around Eqn Number 4 ??

Any help would be appreciated. 
Thanks

**Comment by Eilene** [comment]
Hi,
I implement GWNN via Equation (9) and Equation (10),  The $F^m$ in Equation (10) is the $\Psi_s^{-1}y$ in Equation (4). In "class Wavelet_Convolution" of "layers.py", I implement Equation (9) and (10).  The below code in function "__init__" is used to init parameters $W$ and $F^m$,
 
      self.vars['weights_' + str(0)] = glorot([input_dim, output_dim], name='weights_' + str(0))
      self.vars['kernel'] = ones([self.node_num], name='kernel')

In function "_call", I implement graph convolution via the following code. Note that self.support[0] = $\Psi_s$, self.support[1] = $\Psi_s^{-1}$, :

        supports=tf.matmul(tf.sparse_tensor_to_dense(self.support[0]),tf.diag(self.vars['kernel']),
                         a_is_sparse=True,b_is_sparse=True)
        supports=tf.matmul(supports,tf.sparse_tensor_to_dense(self.support[1]),
                         a_is_sparse=True,b_is_sparse=True)
        pre_sup = dot(x, self.vars['weights_' + str(0)],sparse=self.sparse_inputs)
        output = dot(supports,pre_sup)

Thank you for your attention!

**Comment by abhi-rf** [comment]
Thanks for the response. Also, there seems to be a slight issue, when I make the wavelet_s, and dataset to citeseer  and the required threshold changes in train.py, or pubmed dataset instead of cora, the program fails, indicating errors at where it saves checkpoint. This is the error message :


**************Constructing wavelet finished, Begin training**************
2019-03-30 09:47:21.926827: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "train.py", line 169, in <module>
    saver.restore(sess, checkpt_old_file)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1574, in restore
    err, "a mismatch between the current graph and the graph")
tensorflow.python.framework.errors_impl.InvalidArgumentError: Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [16,6] rhs shape= [16,7]
	 [[{{node save/Assign_13}} = Assign[T=DT_FLOAT, _class=["loc:@wavelet_neural_network/wavelet_convolution_2_vars/weights_0"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](wavelet_neural_network/wavelet_convolution_2_vars/weights_0/Adam_1, save/RestoreV2:13)]]

Caused by op u'save/Assign_13', defined at:
  File "train.py", line 124, in <module>
    saver = tf.train.Saver()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1094, in __init__
    self.build()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1106, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1143, in _build
    build_save=build_save, build_restore=build_restore)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 787, in _build_internal
    restore_sequentially, reshape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 428, in _AddRestoreOps
    assign_ops.append(saveable.restore(saveable_tensors, shapes))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 119, in restore
    self.op.get_shape().is_fully_defined())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/state_ops.py", line 221, in assign
    validate_shape=validate_shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_state_ops.py", line 61, in assign
    use_locking=use_locking, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3254, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1750, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [16,6] rhs shape= [16,7]
	 [[{{node save/Assign_13}} = Assign[T=DT_FLOAT, _class=["loc:@wavelet_neural_network/wavelet_convolution_2_vars/weights_0"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](wavelet_neural_network/wavelet_convolution_2_vars/weights_0/Adam_1, save/RestoreV2:13)]]

**Comment by Eilene** [comment]
I load a pre-trained model for Cora dataset, and the parameter "Pretrain_model_cora" in Line 17 of "train.py" is used to indicate that the pre-tained model is used. However, this pre-trained model can only be used in Cora dataset. So if you want to run GWNN in Citeseer, please set the parameter "Pretrain_model_cora" to False, then the GWNN for Citeseer will be trained.

Hope this answer can solve you question.

Best regards

**Comment by abhi-rf** [comment]
Hello,

It worked, however when I ran it without pre trained ,model for cora and citeseer, I was not getting the same accuracy as mentioned, despite making changes of s and t. Kindly help me with it.
